sonar.organization=vitorbansen
sonar.projectKey=vitorbansen_Portifolio-MedSync

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**,**/*.d.ts

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
